//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int id { get; set; }
        public Nullable<int> rate { get; set; }
        public string opinion_description { get; set; }
        public Nullable<System.DateTime> opinion_date { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
