//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Opinions = new HashSet<Opinion>();
            this.Rankings = new HashSet<Ranking>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> producer_id { get; set; }
        public string shop_location { get; set; }
        public Nullable<double> average_price { get; set; }
        public string product_information { get; set; }
        public string picture { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Opinion> Opinions { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual ICollection<Ranking> Rankings { get; set; }
    }
}
