//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Opinions = new HashSet<Opinion>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Subscriptions1 = new HashSet<Subscription>();
        }
    
        public int id { get; set; }
        public string nick { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public string name { get; set; }
        public Nullable<double> rank { get; set; }
    
        public virtual ICollection<Opinion> Opinions { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Subscription> Subscriptions1 { get; set; }
    }
}
